//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeSuggestion
    {
        public int SuggestionId { get; set; }
        public Nullable<int> SubmissionId { get; set; }
        public string SuggestionText { get; set; }
        public string SuggestionType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual CodeSubmission CodeSubmission { get; set; }
    }
}
